SELECT  SalesOrderID,
        SalesOrderDetailID,
        ProductID,
        SpecialOfferID,
        UnitPrice,
        UnitPriceDiscount,
        LineTotal,
        OrderQty,
        OrderDate,
        DueDate,
        ShipDate,
        OnlineOrderFlag,
        CustomerID,
        TerritoryID,
        BillToAddressID,
        ShipToAddressID,
        ShipMethodID,
        OnTimeShipping,
        SalesType,
        ShipTimeID,
        SalesPersonID
FROM {{ ref('merg_FactSales') }}